### ISSUE TITLE
--charset=utf8 does not work

### ISSUE THREAD

**Issue by sshine** [DK-Hostmaster/whois-service-specification#4]
In [Example domain name query using UTF-8](https://github.com/DK-Hostmaster/whois-service-specification#example-domain-name-query-using-utf-8), 

```
$ whois " --charset=utf8 æøåöäüé.dk"
...
No entries found for the selected source.
```

while both of the following work:

- `whois xn--4cabco7dk5a.dk`
- `whois "$(echo -n "æøåöäüé.dk" | iconv -f UTF-8 -t ISO-8859-15)"`

*(The latter should also verify that the example above is, in fact, made with UTF-8.)*

Should this be regarded a bug in the way DK-Hostmaster's WHOIS server handles UTF-8, or a bug in the specification, or is there a detail in the example request I have misunderstood?

**Comment by sshine** [comment]
It turns out that `whois` Ubuntu 18.04 does not ship with IDN support.

**Comment by jonasbn** [comment]
I have updated the specification with a clause on feature support. The examples where created a long time ago on MacOS 10.11. Since the `whois` clients vary in implementation the DK Hostmaster specific features might not be supported. The RFC describing the WHOIS protocol only dictates text as format and ASCII as encoding, so the features for support for ISO-8859-1 and UTF-8 are local implementation and apparently with limited support :-/
